AgaKhanFoundation/WCB

.eslintrc.yml, .gitignore, .travis.yml, README.md, package.json, test/routes-specs.js
=> #7: Set up ESLint

.dockerignore, Dockerfile, README.md
- Added Docker File to build the docker container
- Added .dockerignore
=> Adding Dockerfile

README.md, lib/models/accomplishment.js, lib/models/destinations.js, lib/models/index.js, lib/models/participant.js, lib/models/record.js, lib/models/source.js, lib/models/sponsor.js, lib/models/sponsorship.js, lib/models/team.js, lib/routes.js, package.json, schema/mysql.sql, settings/test.json, test/db-specs.js
Please review @compnerd @alykhank @moizjv 
- Added models
- Added test to demonstrate how to create db entry.
=> Adding models and changing schema little bit

README.md
@moizjv @alykhank  Please review.
=> Changed docker run commands

.gitignore, README.md, lib/models/accomplishment.js, lib/models/destinations.js, lib/models/index.js, lib/models/participant.js, lib/models/record.js, lib/models/source.js, lib/models/sponsor.js, lib/models/sponsorship.js, lib/models/team.js, lib/routes.js, lib/server.js, package.json, settings/dev.json, test/db-specs.js, test/routes-specs.js
Resolves #3.
* `GET /teams` => all teams
* `GET /teams/:id` => single team
* `POST /teams "name=$name"` => create team with $name
* `PATCH /teams/:id "name=$name"` => change team name to $name
* `DELETE /teams/:id` => delete team
=> #3 Implement team endpoints

lib/models/index.js, settings/prod.json, settings/staging.json
@alykhank please review, 
These changes are so staging can access mysql db
=> Updating username and password for staging

lib/models/achievement.js, lib/models/achievements.js, lib/models/cause.js, lib/models/donor.js, lib/models/donors.js, lib/models/events.js, lib/models/index.js, lib/models/locality.js, lib/models/participants.js, lib/models/records.js, lib/models/sources.js, lib/models/sponsor.js, lib/models/sponsors.js, lib/models/team.js, lib/routes/achievement.js, lib/routes/achievements.js, lib/routes/teams.js, lib/server.js, schema/mysql.sql, test/achievement-specs.js, test/achievements-specs.js
=> Create achievement and achievements endpoints

lib/models/sources.js, lib/routes/sources.js, lib/server.js, test/sources-specs.js
=> Add sources endpoints

lib/routes/causes.js, lib/server.js, test/cause-specs.js
=> Add causes endpoints

lib/models/donors.js, lib/models/index.js, lib/models/participant.js, lib/models/records.js, lib/models/sponsors.js, lib/routes/participants.js, lib/routes/teams.js, schema/mysql.sql, test/participants-specs.js
* Resolve #47
* Rename participants model to participant for consistency
=> Include team members in participants array

lib/models/achievement.js, lib/models/achievements.js, lib/models/cause.js, lib/models/donor.js, lib/models/donors.js, lib/models/event.js, lib/models/locality.js, lib/models/participant.js, lib/models/record.js, lib/models/records.js, lib/models/source.js, lib/models/sponsor.js, lib/models/sponsors.js, lib/models/team.js, lib/routes/sources.js, schema/mysql.sql, test/causes-specs.js, test/sources-specs.js, test/teams-specs.js
* Rename entity tables to be singular (join tables are still intentionally plural)
* Describe tests consistently
* Remove explicit length qualifiers from DataTypes
=> Refactor database schema

lib/models/index.js, lib/routes/achievement.js, lib/routes/teams.js, test/achievement-specs.js, test/teams-specs.js
* Return achievement info in /teams endpoint and vice versa
=> Establish team/achievement associations

README.md, config/sequelize.json, lib/migrations/1-event-name-unique.js, lib/models/event.js, lib/routes/achievements.js, lib/routes/events.js, lib/routes/participants.js, lib/server.js, package.json, test/events-specs.js, test/routes-specs.js, utils/client.sh
=> events: add endpoint

utils/client.py, utils/dev
Add client.py that supports all current endpoints
* Usage: `./utils/client.py <entity> <c|r|u|d> [...]`
* Optionally specify env vars SCHEME, SERVER, PORT
* Use `./utils/dev` to interact with local env
=> Add python client

lib/routes/participants.js, lib/routes/teams.js, test/participants-specs.js, test/teams-specs.js
Resolves #4.
* `/participants/:fbid/stats => {'distance': N}`
* `/teams/:id/stats => {'distance': N}`
=> Return stats for participants and teams

.eslintrc.yml, .travis.yml, config/config.json, lib/models/index.js, lib/routes/participants.js, package-lock.json, package.json
* Set eslint object-curly-spacing: never
* Disable Sequelize logging for tests
=> Update developer dependencies and coverage tool

charts/wcb-dev/.helmignore, charts/wcb-dev/Chart.yaml, charts/wcb-dev/rbac-config.yaml, charts/wcb-dev/templates/NOTES.txt, charts/wcb-dev/templates/_helpers.tpl, charts/wcb-dev/templates/deployment.yaml, charts/wcb-dev/templates/ingress.yaml, charts/wcb-dev/templates/service.yaml, charts/wcb-dev/values.yaml
resolves #74.
- Adding template for getting started with k8 deployment via helm.
- This is intended for dev/staging.
TODO:
- Will require CI to test the pipeline eventually.
=> add dev helm chart

.travis.yml, Dockerfile, README.md, package-lock.json, package.json
Update the Node.js runtime version to 10.16.3 which is the recommended long-term support version. See https://nodejs.org/.
=> Update Node.js to 10.16.3 LTS version

lib/migrations/4-team-creator.js, lib/models/index.js, lib/routes/teams.js, test/teams-specs.js, utils/client.py
=> Add creator association to team model

lib/migrations/5-participant-event.js, lib/models/index.js, lib/models/participant_event.js, lib/routes/commitments.js, lib/server.js, test/commitments-specs.js, utils/client.py
=> Add endpoint to track participant's step commitment for each event

package-lock.json
Ran `npm audit fix` to update the offending module (and dependency) tree
=> Resolve handlebars module vulnerability

README.md, lib/server.js, package-lock.json, package.json, test/routes-specs.js, utils/client.py
Resolves #25.
* Check for `SERVER_PASSWORD` env var in `.env` for local development and client.py
=> Secure endpoints with basic auth password

.dockerignore
Ensure dev db is not included in Docker images
=> Add sqlite files to dockerignore

Makefile
=> Removing test versioning, added appropriate versioning

Makefile, package-lock.json, package.json
- Reset the version to match the current git tag
- Fixing the Makefile to reflect right version(npm version) in Quay repository
=> Fixed Makefile to reflect proper version in Quay

azure-pipelines.yml, package.json
Attempt to add coverage reporting to azure
=> Update azure-pipelines.yml for Azure Pipelines

lib/migrations/10-achievement-2.js, lib/migrations/10-achievement-fields.js, lib/models/achievement.js, lib/routes/achievement.js, test/achievement-specs.js, utils/client.py
Additional attributes for /achievement response
Flowed tests text to be more readable or previous PR comment
Rebased on upstream master without causing duplicate history
=> Additional attributes for /achievement response

lib/routes/participants.js, lib/services/admin.js, package-lock.json, package.json, test/participants-specs.js, test/routes-specs.js, utils/client.py
Also need to add the firebase json key and two environment variables to builds: 
- `GOOGLE_APPLICATION_CREDENTIALS` which needs to be the path to the firebase json file
- `FIREBASE_NAME` which is the name of our firebase account
=> Firebase Auth

README.md, azure-pipelines.yml, package-lock.json, package.json
Update the Node.js runtime version to 14.15.4 which is the recommended long-term support version. See https://nodejs.org/.
=> Update Node.js to 14.15.4 LTS version

README.md, azure-pipelines.yml, package-lock.json, package.json
Update the Node.js runtime version to 14.19.0
=> Update Node.js to 14.19.0
